name: 🐛 Bug report
description: Create a report to help us improve
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue 🙏.
        Before you submit, please search the issue tracker to prevent duplicates as a similar issue might already exist.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Describe the steps we have to take to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: 1.2.3
    validations:
      required: true
  - type: dropdown
    id: platform-client
    attributes:
      label: What client platform(s) are you seeing the problem on?
      multiple: true
      options:
        - Android
        - Linux
        - Windows
    validations:
      required: true
  - type: dropdown
    id: platform-server
    attributes:
      label: What server platform(s) are you seeing the problem on?
      multiple: true
      options:
        - Mbin
        - Lemmy
        - PieFed
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
