name: Pull request tests

permissions:
  contents: write

on: pull_request

jobs:
  test-android-build:
    name: Test android build
    runs-on: ubuntu-latest
    steps:
      - name: Install android dependencies
        if: matrix.target == 'android'
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin

      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Flutter app
        run: |
          dart run build_runner build
          flutter build -v apk --split-per-abi
  test-linux-build:
    name: Test linux build
    runs-on: ubuntu-latest
    steps:
      - name: Install linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev libmpv-dev mpv

      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Flutter app
        run: |
          dart run build_runner build
          flutter build -v linux
